-- Enable RLS on all tables that don't have it yet
ALTER TABLE IF EXISTS establishments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reviews_raw ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_establishment ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS établissements ENABLE ROW LEVEL SECURITY;