-- Create table for storing raw reviews from multiple sources
CREATE TABLE IF NOT EXISTS public.reviews_raw (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id text NOT NULL,
  source text NOT NULL,              -- 'google' | 'yelp' | ...
  source_ref text,                   -- id de l'avis côté source
  author text,
  rating numeric,
  text text,
  url text,
  created_at timestamptz,
  hash text UNIQUE,                  -- pour dédupe
  inserted_at timestamptz DEFAULT now(),
  reviewed_at timestamptz            -- alias for created_at to match existing usage
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS reviews_raw_place_idx ON public.reviews_raw(place_id);
CREATE INDEX IF NOT EXISTS reviews_raw_source_idx ON public.reviews_raw(source);
CREATE INDEX IF NOT EXISTS reviews_raw_hash_idx ON public.reviews_raw(hash);

-- Enable RLS
ALTER TABLE public.reviews_raw ENABLE ROW LEVEL SECURITY;

-- Create policies to match existing review_insights patterns
CREATE POLICY "Users can view reviews for their establishments" 
ON public.reviews_raw 
FOR SELECT 
USING (place_id IN (
  SELECT user_establishment.place_id
  FROM user_establishment
  WHERE user_establishment.user_id = auth.uid()
));

CREATE POLICY "Service can insert reviews" 
ON public.reviews_raw 
FOR INSERT 
WITH CHECK (true);