// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njtvgofnlumfxwtxdnaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qdHZnb2ZubHVtZnh3dHhkbmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDMyNDYsImV4cCI6MjA3MTg3OTI0Nn0.RkTu7XG28ToVsDe8nOw_76H1Qwhf3etT7GJx1vS_GHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});